export const uiStrings = {
  en: {
    viewRecipe: 'View Recipe',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    logout: 'Logout',
    adminPanel: 'Admin Panel',
    rating: 'Rating',
    comments: 'Comments',
    addComment: 'Add Comment',
    submitComment: 'Submit',
    brewDashboard: 'Brew Dashboard',
    waterTemp: 'Water Temperature',
    totalTime: 'Total Brew Time',
    ratio: 'Ratio',
    pours: 'Pours',
    origin: 'Origin',
    variety: 'Variety',
    processing: 'Processing',
    roastLevel: 'Roast Level',
    elevation: 'Elevation',
    addBean: 'Add New Bean',
    deleteBean: 'Delete',
    editBean: 'Edit',
    manageComments: 'Manage Comments',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    welcomeBack: 'Welcome Back',
    createAccount: 'Create Account',
  },
  ar: {
    viewRecipe: 'عرض الوصفة',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    logout: 'تسجيل الخروج',
    adminPanel: 'لوحة الإدارة',
    rating: 'التقييم',
    comments: 'التعليقات',
    addComment: 'أضف تعليقاً',
    submitComment: 'إرسال',
    brewDashboard: 'لوحة التحضير',
    waterTemp: 'درجة حرارة الماء',
    totalTime: 'وقت التحضير الكلي',
    ratio: 'النسبة',
    pours: 'السكبات',
    origin: 'المنشأ',
    variety: 'النوع',
    processing: 'المعالجة',
    roastLevel: 'درجة التحميص',
    elevation: 'الارتفاع',
    addBean: 'إضافة حبة جديدة',
    deleteBean: 'حذف',
    editBean: 'تعديل',
    manageComments: 'إدارة التعليقات',
    delete: 'حذف',
    save: 'حفظ',
    cancel: 'إلغاء',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    welcomeBack: 'مرحباً بعودتك',
    createAccount: 'إنشاء حساب',
  },
}
