export const uiStrings = {
  en: {
    viewRecipe: 'View Recipe',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    logout: 'Logout',
    adminPanel: 'Admin Panel',
    rating: 'Rating',
    comments: 'Comments',
    addComment: 'Add Comment',
    submitComment: 'Submit',
    brewDashboard: 'Brew Dashboard',
    waterTemp: 'Water Temperature',
    totalTime: 'Total Brew Time',
    ratio: 'Ratio',
    pours: 'Pours',
    origin: 'Origin',
    variety: 'Variety',
    processing: 'Processing',
    roastLevel: 'Roast Level',
    elevation: 'Elevation',
    addBean: 'Add New Bean',
    deleteBean: 'Delete',
    editBean: 'Edit',
    manageComments: 'Manage Comments',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    welcomeBack: 'Welcome Back',
    createAccount: 'Create Account',
    heroTitle1: 'Recipes worth',
    heroTitle2: 'brewing twice',
    heroTagline: 'A pour-over journal',
    heroDesc:
      'A small, opinionated vault of single-origin beans and the V60 recipes that pull the best out of them. Tap a card to see the dial-in.',
    beansCount: (n) => `${n} beans`,
    theCollection: 'The Collection',
    suggestRecipe: 'Suggest a Recipe',
    submitSuggestion: 'Submit Suggestion',
    mySuggestions: 'My Suggestions',
    pending: 'Pending',
    accepted: 'Accepted',
    rejected: 'Rejected',
    communityRecipes: 'Community Recipes',
    suggestionSubmitted: 'Your suggestion has been submitted for review',
    makeMainRecipe: 'Made Main Recipe',
    suggestBean: 'Suggest a Coffee Bean',
    beanDetails: 'Bean Details',
    includeRecipe: 'Include a V60 Recipe',
    submitBeanSuggestion: 'Submit Bean Suggestion',
    beanSuggestions: 'Bean Suggestions',
    beanSuggestionSubmitted:
      'Your bean suggestion has been submitted for review',
    myFavorites: 'My Favorites',
    mostLoved: 'Most Loved Beans',
    noFavorites: 'No favorites yet — heart a bean to save it here',
    noRatings: 'No ratings yet',
    saveToFavorites: 'Save to Favorites',
    saved: 'Saved',
    searchPlaceholder: 'Search beans...',
    filterRoast: 'Roast Level',
    filterOrigin: 'Origin',
    sortBy: 'Sort By',
    sortDefault: 'Default',
    sortHighestRated: 'Highest Rated',
    sortMostFavorited: 'Most Favorited',
    sortNewest: 'Newest Added',
    showingResults: (x, y) => `Showing ${x} of ${y} beans`,
    noResults: 'No beans match your search',
    clearAll: 'Clear all',
    allRoasts: 'All Roasts',
    allOrigins: 'All Origins',
    ourRoasteries: 'Our Roasteries',
    roastery: 'Roastery',
    noRoastery: 'None / Unknown',
    manageRoasteries: 'Manage Roasteries',
    addRoastery: 'Add New Roastery',
    beanCount: (n) => `${n} beans`,
    signInToComment: 'Sign in to leave a comment',
    signInToRate: 'Sign in to rate this bean',
    signInToFavorite: 'Sign in to save favorites',
    searchRoasteryBeans: 'Search beans in this roastery...',
    showingRoasteryResults: (x, y) => `Showing ${x} of ${y} beans`,
  },
  ar: {
    viewRecipe: 'عرض الوصفة',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    logout: 'تسجيل الخروج',
    adminPanel: 'لوحة الإدارة',
    rating: 'التقييم',
    comments: 'التعليقات',
    addComment: 'أضف تعليقاً',
    submitComment: 'إرسال',
    brewDashboard: 'لوحة التحضير',
    waterTemp: 'درجة حرارة الماء',
    totalTime: 'وقت التحضير الكلي',
    ratio: 'النسبة',
    pours: 'السكبات',
    origin: 'المنشأ',
    variety: 'النوع',
    processing: 'المعالجة',
    roastLevel: 'درجة التحميص',
    elevation: 'الارتفاع',
    addBean: 'إضافة حبة جديدة',
    deleteBean: 'حذف',
    editBean: 'تعديل',
    manageComments: 'إدارة التعليقات',
    delete: 'حذف',
    save: 'حفظ',
    cancel: 'إلغاء',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    welcomeBack: 'مرحباً بعودتك',
    createAccount: 'إنشاء حساب',
    heroTitle1: 'وصفات تستحق',
    heroTitle2: 'التحضير مرتين',
    heroTagline: 'مجلة القهوة المقطرة',
    heroDesc:
      'مجموعة صغيرة ومختارة من حبوب القهوة أحادية المصدر ووصفات V60 التي تستخرج أفضل ما فيها. اضغط على بطاقة لترى التفاصيل.',
    beansCount: (n) => `${n} حبة`,
    theCollection: 'المجموعة',
    suggestRecipe: 'اقتراح وصفة',
    submitSuggestion: 'إرسال الاقتراح',
    mySuggestions: 'اقتراحاتي',
    pending: 'قيد المراجعة',
    accepted: 'مقبول',
    rejected: 'مرفوض',
    communityRecipes: 'وصفات المجتمع',
    suggestionSubmitted: 'تم إرسال اقتراحك للمراجعة',
    makeMainRecipe: 'تم اعتمادها وصفة رئيسية',
    suggestBean: 'اقتراح حبة قهوة',
    beanDetails: 'تفاصيل الحبة',
    includeRecipe: 'إضافة وصفة V60',
    submitBeanSuggestion: 'إرسال اقتراح الحبة',
    beanSuggestions: 'اقتراحات الحبوب',
    beanSuggestionSubmitted: 'تم إرسال اقتراح الحبة للمراجعة',
    myFavorites: 'المفضلة',
    mostLoved: 'الحبوب الأكثر حباً',
    noFavorites: 'لا مفضلات بعد — اضغط على القلب لحفظ الحبة',
    noRatings: 'لا تقييمات بعد',
    saveToFavorites: 'حفظ في المفضلة',
    saved: 'تم الحفظ',
    searchPlaceholder: 'ابحث عن حبة...',
    filterRoast: 'درجة التحميص',
    filterOrigin: 'المنشأ',
    sortBy: 'ترتيب حسب',
    sortDefault: 'الافتراضي',
    sortHighestRated: 'الأعلى تقييماً',
    sortMostFavorited: 'الأكثر حباً',
    sortNewest: 'الأحدث',
    showingResults: (x, y) => `عرض ${x} من ${y} حبة`,
    noResults: 'لا توجد حبوب تطابق بحثك',
    clearAll: 'مسح الكل',
    allRoasts: 'كل درجات التحميص',
    allOrigins: 'كل المناشئ',
    ourRoasteries: 'المحامص لدينا',
    roastery: 'المحمصة',
    noRoastery: 'غير محدد',
    manageRoasteries: 'إدارة المحامص',
    addRoastery: 'إضافة محمصة جديدة',
    beanCount: (n) => `${n} حبوب`,
    signInToComment: 'سجل دخولك لترك تعليق',
    signInToRate: 'سجل دخولك لتقييم هذه الحبة',
    signInToFavorite: 'سجل دخولك لحفظ المفضلة',
    searchRoasteryBeans: 'ابحث عن حبة في هذه المحمصة...',
    showingRoasteryResults: (x, y) => `عرض ${x} من ${y} حبة`,
  },
}
