export const uiStrings = {
  en: {
    viewRecipe: 'View Recipe',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    logout: 'Logout',
    adminPanel: 'Admin Panel',
    rating: 'Rating',
    comments: 'Comments',
    addComment: 'Add Comment',
    submitComment: 'Submit',
    brewDashboard: 'Brew Dashboard',
    waterTemp: 'Water Temperature',
    totalTime: 'Total Brew Time',
    ratio: 'Ratio',
    pours: 'Pours',
    origin: 'Origin',
    variety: 'Variety',
    processing: 'Processing',
    roastLevel: 'Roast Level',
    elevation: 'Elevation',
    addBean: 'Add New Bean',
    deleteBean: 'Delete',
    editBean: 'Edit',
    manageComments: 'Manage Comments',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    welcomeBack: 'Welcome Back',
    createAccount: 'Create Account',
    heroTitle1: 'Recipes worth',
    heroTitle2: 'brewing twice',
    heroTagline: 'A pour-over journal',
    heroDesc:
      'A small, opinionated vault of single-origin beans and the V60 recipes that pull the best out of them. Tap a card to see the dial-in.',
    beansCount: (n) => `${n} beans`,
    theCollection: 'The Collection',
    suggestRecipe: 'Suggest a Recipe',
    submitSuggestion: 'Submit Suggestion',
    mySuggestions: 'My Suggestions',
    pending: 'Pending',
    accepted: 'Accepted',
    rejected: 'Rejected',
    communityRecipes: 'Community Recipes',
    suggestionSubmitted: 'Your suggestion has been submitted for review',
    makeMainRecipe: 'Made Main Recipe',
    suggestBean: 'Suggest a Coffee Bean',
    beanDetails: 'Bean Details',
    includeRecipe: 'Include a V60 Recipe',
    submitBeanSuggestion: 'Submit Bean Suggestion',
    beanSuggestions: 'Bean Suggestions',
    beanSuggestionSubmitted:
      'Your bean suggestion has been submitted for review',
  },
  ar: {
    viewRecipe: 'عرض الوصفة',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    logout: 'تسجيل الخروج',
    adminPanel: 'لوحة الإدارة',
    rating: 'التقييم',
    comments: 'التعليقات',
    addComment: 'أضف تعليقاً',
    submitComment: 'إرسال',
    brewDashboard: 'لوحة التحضير',
    waterTemp: 'درجة حرارة الماء',
    totalTime: 'وقت التحضير الكلي',
    ratio: 'النسبة',
    pours: 'السكبات',
    origin: 'المنشأ',
    variety: 'النوع',
    processing: 'المعالجة',
    roastLevel: 'درجة التحميص',
    elevation: 'الارتفاع',
    addBean: 'إضافة حبة جديدة',
    deleteBean: 'حذف',
    editBean: 'تعديل',
    manageComments: 'إدارة التعليقات',
    delete: 'حذف',
    save: 'حفظ',
    cancel: 'إلغاء',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    welcomeBack: 'مرحباً بعودتك',
    createAccount: 'إنشاء حساب',
    heroTitle1: 'وصفات تستحق',
    heroTitle2: 'التحضير مرتين',
    heroTagline: 'مجلة القهوة المقطرة',
    heroDesc:
      'مجموعة صغيرة ومختارة من حبوب القهوة أحادية المصدر ووصفات V60 التي تستخرج أفضل ما فيها. اضغط على بطاقة لترى التفاصيل.',
    beansCount: (n) => `${n} حبة`,
    theCollection: 'المجموعة',
    suggestRecipe: 'اقتراح وصفة',
    submitSuggestion: 'إرسال الاقتراح',
    mySuggestions: 'اقتراحاتي',
    pending: 'قيد المراجعة',
    accepted: 'مقبول',
    rejected: 'مرفوض',
    communityRecipes: 'وصفات المجتمع',
    suggestionSubmitted: 'تم إرسال اقتراحك للمراجعة',
    makeMainRecipe: 'تم اعتمادها وصفة رئيسية',
    suggestBean: 'اقتراح حبة قهوة',
    beanDetails: 'تفاصيل الحبة',
    includeRecipe: 'إضافة وصفة V60',
    submitBeanSuggestion: 'إرسال اقتراح الحبة',
    beanSuggestions: 'اقتراحات الحبوب',
    beanSuggestionSubmitted: 'تم إرسال اقتراح الحبة للمراجعة',
  },
}
